/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import service.ReceitaService;
import dominio.Receita;
import java.util.ArrayList;
import dominio.Ingrediente;
import java.util.List;
import service.IngredienteService;
import validacoes.ValidacaoIngrediente;
import validacoes.ValidacaoPessoa;

/**
 *
 * @author Vinicius
 */
public class EditarReceitaGUI extends javax.swing.JFrame {
    
    ReceitaService receitaService= new ReceitaService();
    IngredienteService ingredienteService= new IngredienteService();
    private ArrayList<Ingrediente> listaIngredientesCadastrar = new ArrayList<Ingrediente>();

    /**
     * Creates new form ReceitaCadastro
     */
    public EditarReceitaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listaIngredientes = listaIngredientes= new ArrayList<Ingrediente>();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codpessoaReceitaTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        codreceitaTf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tituloreceitaTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        datareceitaTf = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modepreparoTf = new javax.swing.JTextArea();
        botaoEditarReceita = new javax.swing.JToggleButton();
        botaoCancela = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabaleIngredientes = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        descricaoIngredienteTf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        quantidadeIngredienteTf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        unidadeIngredienteTf = new javax.swing.JTextField();
        botaoAddIngrediente = new javax.swing.JButton();
        botaoExcluirIngrediente = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        seqIngredienteTf = new javax.swing.JTextField();

        listaIngredientes = org.jdesktop.observablecollections.ObservableCollections.observableList(listaIngredientes);

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MV Boli", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Editar Receita");

        jLabel2.setText("Codigo da Pessoa: ");

        jLabel3.setText("Codigo da Receita:");

        codreceitaTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codreceitaTfActionPerformed(evt);
            }
        });

        jLabel4.setText("Titulo:");

        jLabel5.setText("Data: ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Modo de Preparo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        modepreparoTf.setColumns(20);
        modepreparoTf.setRows(5);
        jScrollPane1.setViewportView(modepreparoTf);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        botaoEditarReceita.setText("Atualizar");
        botaoEditarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarReceitaActionPerformed(evt);
            }
        });

        botaoCancela.setText("Cancelar");
        botaoCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelaActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ingredientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listaIngredientes, tabaleIngredientes);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${seqIngrdiente}"));
        columnBinding.setColumnName("Seq Ingrdiente");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descricao}"));
        columnBinding.setColumnName("Descricao");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${quantidade}"));
        columnBinding.setColumnName("Quantidade");
        columnBinding.setColumnClass(Float.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${unidade}"));
        columnBinding.setColumnName("Unidade");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane2.setViewportView(tabaleIngredientes);

        jLabel6.setText("Descrição: ");

        descricaoIngredienteTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoIngredienteTfActionPerformed(evt);
            }
        });

        jLabel7.setText("Quantidade: ");

        jLabel8.setText("Unidade: ");

        botaoAddIngrediente.setText("Add Ingrediente");
        botaoAddIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddIngredienteActionPerformed(evt);
            }
        });

        botaoExcluirIngrediente.setText("Exluir Ingrediente");
        botaoExcluirIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirIngredienteActionPerformed(evt);
            }
        });

        jLabel10.setText("Seq. Ingrediente: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descricaoIngredienteTf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botaoAddIngrediente)
                                    .addComponent(quantidadeIngredienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(unidadeIngredienteTf))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(botaoExcluirIngrediente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seqIngredienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(seqIngredienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricaoIngredienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(quantidadeIngredienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(unidadeIngredienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAddIngrediente)
                    .addComponent(botaoExcluirIngrediente))
                .addGap(183, 183, 183))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tituloreceitaTf))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(codpessoaReceitaTf, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel5))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codreceitaTf)
                            .addComponent(datareceitaTf))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(botaoEditarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(botaoCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codpessoaReceitaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(codreceitaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(datareceitaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tituloreceitaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEditarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codreceitaTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codreceitaTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codreceitaTfActionPerformed

    private void botaoEditarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarReceitaActionPerformed
        // TODO add your handling code here:
        Receita receita = new Receita();
        
        String codReceitaString = String.valueOf(this.codreceitaTf.getText());
        String codPessoaString = String.valueOf(this.codpessoaReceitaTf.getText());
        String tituloString = String.valueOf(this.tituloreceitaTf.getText());
        String modopreparoString = String.valueOf(this.modepreparoTf.getText());
        String dataString = String.valueOf(this.datareceitaTf.getText());
        
        receita.setCodReceita(codReceitaString);
        receita.setCodigoPessoa(codPessoaString);
        receita.setTitulo(tituloString);
        receita.setData(dataString);
        receita.setModoPreparo(modopreparoString);
        
        
        boolean existReceita= receitaService.existeReceita(receita);
        boolean existPessoa= ValidacaoPessoa.existePessoaCadastrada(codPessoaString);
        
        if(!codReceitaString.equals("")){
            if( !existReceita && existPessoa){
                
                
                for(int i=0; i<this.listaIngredientes.size(); i++){
                    Ingrediente ing= this.listaIngredientes.get(i);
                    ing.setCodigoReceita(codReceitaString);
                    this.listaIngredientesCadastrar.add(ing);
                }
                receitaService.atualizarReceita(receita);
                ingredienteService.cadastrarListaIngrediente(listaIngredientesCadastrar);
                this.listaIngredientes.clear();
                this.listaIngredientesCadastrar.clear();
                
            }else{
                //caso ja existir receita com o mesmo codigo
                //Não existir pessoa cadastrada
            }
            
            
        }else{
           // Caso o codigo da receita for nulo

            
        }
        
        
    }//GEN-LAST:event_botaoEditarReceitaActionPerformed

    private void descricaoIngredienteTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoIngredienteTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoIngredienteTfActionPerformed

    private void botaoAddIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddIngredienteActionPerformed
        // TODO add your handling code here:
        String descricaoString= String.valueOf(this.descricaoIngredienteTf.getText());
        String unidadeString= String.valueOf(this.unidadeIngredienteTf.getText());
        
        
        if(this.quantidadeIngredienteTf.getText().equals("") || this.quantidadeIngredienteTf.getText().equals("")){
            //Mensagem de erro
        
        } else {
            int seqIngredienteInt = Integer.valueOf(this.seqIngredienteTf.getText());
            Float quantidadeFloat = Float.valueOf(this.quantidadeIngredienteTf.getText());
            
            Ingrediente ingrediente = new Ingrediente();
            
            ingrediente.setDescricao(descricaoString);
            ingrediente.setUnidade(unidadeString);
            ingrediente.setQuantidade(quantidadeFloat);
            ingrediente.setSeqIngrdiente(seqIngredienteInt);
            
            boolean validacao = ValidacaoIngrediente.verificarIngredienteLista(this.listaIngredientes, ingrediente);
            
            if(!validacao){
                this.listaIngredientes.add(ingrediente);
            }else{
                //Mensagem de erro;
            }
        }
    }//GEN-LAST:event_botaoAddIngredienteActionPerformed

    private void botaoExcluirIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirIngredienteActionPerformed
        
        int ingredienteSelecionado = this.tabaleIngredientes.getSelectedRow();
        
        this.listaIngredientes.remove(ingredienteSelecionado);
        
        
        
    }//GEN-LAST:event_botaoExcluirIngredienteActionPerformed

    private void botaoCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelaActionPerformed
        GerenciadorReceitasGUI gerenciadorR = new GerenciadorReceitasGUI();
        gerenciadorR.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(EditarReceitaGUI.EXIT_ON_CLOSE);
    }//GEN-LAST:event_botaoCancelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarReceitaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarReceitaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarReceitaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarReceitaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarReceitaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAddIngrediente;
    private javax.swing.JToggleButton botaoCancela;
    private javax.swing.JToggleButton botaoEditarReceita;
    private javax.swing.JButton botaoExcluirIngrediente;
    private javax.swing.JTextField codpessoaReceitaTf;
    private javax.swing.JTextField codreceitaTf;
    private javax.swing.JTextField datareceitaTf;
    private javax.swing.JTextField descricaoIngredienteTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.util.List<Ingrediente> listaIngredientes;
    private javax.swing.JTextArea modepreparoTf;
    private javax.swing.JTextField quantidadeIngredienteTf;
    private javax.swing.JTextField seqIngredienteTf;
    private javax.swing.JTable tabaleIngredientes;
    private javax.swing.JTextField tituloreceitaTf;
    private javax.swing.JTextField unidadeIngredienteTf;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    void setTextField(Receita receita, ArrayList<Ingrediente> listaIngredientesReceita) {
         this.tituloreceitaTf.setText(receita.getTitulo());
        this.codpessoaReceitaTf.setText(receita.getCodigoPessoa());
        this.datareceitaTf.setText(receita.getData());
        this.modepreparoTf.setText(receita.getModoPreparo());
        this.codreceitaTf.setText(receita.getCodReceita());
        
        
        for( int i=0; i<listaIngredientesReceita.size();i++){
            Ingrediente ingrediente= listaIngredientesReceita.get(i);
            this.listaIngredientes.add(ingrediente);
        }
        
    }
}
