/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dominio.Ingrediente;
import dominio.Receita;
import service.ReceitaService;
import java.util.ArrayList;
import java.util.List;
import service.IngredienteService;
/**
 *
 * @author Vinicius
 */
public class GerenciadorReceitasGUI extends javax.swing.JFrame {
    
    private ReceitaService receitaService = new ReceitaService();
    private ArrayList<Receita> todasReceitas= receitaService.getTodasReceitas();
    private Sessao sessao= Sessao.getInstancia();
    /**
     * Creates new form GerenciadorReceitasGUI
     */
    public  GerenciadorReceitasGUI() {
        initComponents();
        for(int i=0; i<this.todasReceitas.size();i++){
            Receita receita= this.todasReceitas.get(i);
            this.listaReceitas.add(receita);
        
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listaReceitas = new ArrayList<Receita>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaReceitas = new javax.swing.JTable();
        botaoAddReceita = new javax.swing.JToggleButton();
        botaoExcluirReceita = new javax.swing.JButton();
        botaoEditarReceita = new javax.swing.JButton();
        botaoVisualizarReceita = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();

        listaReceitas = org.jdesktop.observablecollections.ObservableCollections.observableList(listaReceitas);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listaReceitas, tabelaReceitas);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${titulo}"));
        columnBinding.setColumnName("Titulo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codReceita}"));
        columnBinding.setColumnName("Cod Receita");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${modoPreparo}"));
        columnBinding.setColumnName("Modo Preparo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${data}"));
        columnBinding.setColumnName("Data");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane1.setViewportView(tabelaReceitas);

        botaoAddReceita.setText("Adicionar Receita");
        botaoAddReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddReceitaActionPerformed(evt);
            }
        });

        botaoExcluirReceita.setText("Excluir Receita");
        botaoExcluirReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirReceitaActionPerformed(evt);
            }
        });

        botaoEditarReceita.setText("Editar Receita");
        botaoEditarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarReceitaActionPerformed(evt);
            }
        });

        botaoVisualizarReceita.setText("Visualizar Receita");
        botaoVisualizarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVisualizarReceitaActionPerformed(evt);
            }
        });

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoAddReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoExcluirReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoEditarReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoVisualizarReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoAddReceita)
                        .addGap(27, 27, 27)
                        .addComponent(botaoExcluirReceita)
                        .addGap(31, 31, 31)
                        .addComponent(botaoEditarReceita)
                        .addGap(29, 29, 29)
                        .addComponent(botaoVisualizarReceita)
                        .addGap(33, 33, 33)
                        .addComponent(botaoVoltar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAddReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddReceitaActionPerformed
        ReceitaCadastroGUI receitaCadastroGUI= new ReceitaCadastroGUI();
        receitaCadastroGUI.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(GerenciadorReceitasGUI.EXIT_ON_CLOSE);
    }//GEN-LAST:event_botaoAddReceitaActionPerformed

    private void botaoVisualizarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVisualizarReceitaActionPerformed
        
        try{
        
        ReceitaCadastroGUI cadastroReceitaGUI= new ReceitaCadastroGUI();
        int receitaSelecionada = this.tabelaReceitas.getSelectedRow();
        Receita receita = this.listaReceitas.get(receitaSelecionada);
        ArrayList<Ingrediente> listaIngredientesReceita = new IngredienteService().getListaIngredientesReceita(receita);
        cadastroReceitaGUI.setTextField(receita, listaIngredientesReceita);
        cadastroReceitaGUI.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(GerenciadorReceitasGUI.EXIT_ON_CLOSE);
        
        } catch(ArrayIndexOutOfBoundsException e){
            ErroItem erro = new ErroItem();
            erro.setVisible(true);
        }
        
    }//GEN-LAST:event_botaoVisualizarReceitaActionPerformed

    private void botaoExcluirReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirReceitaActionPerformed
        
        try{
        int receitaSelecionada = this.tabelaReceitas.getSelectedRow();
        Receita receita = this.listaReceitas.get(receitaSelecionada);
        this.receitaService.deletarReceita(receita);
        this.listaReceitas.remove(receitaSelecionada);
        }catch(ArrayIndexOutOfBoundsException e){
            ErroItem erro = new ErroItem();
            erro.setVisible(true);
        }
        
    }//GEN-LAST:event_botaoExcluirReceitaActionPerformed

    private void botaoEditarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarReceitaActionPerformed
        try{  
            EditarReceitaGUI editarReceita= new EditarReceitaGUI();
            int receitaSelecionada = this.tabelaReceitas.getSelectedRow();
            Receita receita = this.listaReceitas.get(receitaSelecionada);
            ArrayList<Ingrediente> listaIngredientesReceita = new IngredienteService().getListaIngredientesReceita(receita);
            editarReceita.setTextField(receita, listaIngredientesReceita);
            editarReceita.setVisible(true);
            this.setVisible(false);
            this.setDefaultCloseOperation(GerenciadorReceitasGUI.EXIT_ON_CLOSE);
           
        }catch(ArrayIndexOutOfBoundsException e){
            ErroItem erro = new ErroItem();
            erro.setVisible(true);
        }
    }//GEN-LAST:event_botaoEditarReceitaActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        InicioGUI inicio = new InicioGUI();
        inicio.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(GerenciadorReceitasGUI.EXIT_ON_CLOSE);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciadorReceitasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciadorReceitasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciadorReceitasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciadorReceitasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciadorReceitasGUI().setVisible(true);
                
                    
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoAddReceita;
    private javax.swing.JButton botaoEditarReceita;
    private javax.swing.JButton botaoExcluirReceita;
    private javax.swing.JButton botaoVisualizarReceita;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private java.util.List<Receita> listaReceitas;
    private javax.swing.JTable tabelaReceitas;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
